README.md, auto_gptq/modeling/_base.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/_utils.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/moss.py, examples/quantization/quant_with_alpaca.py, setup.py
This pr extends `auto_gptq` to support [MOSS](https://github.com/OpenLMLab/MOSS), an open-source tool-augmented conversational language model from Fudan University.
=> Support MOSS model

auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py, examples/README.md, examples/evaluation/run_language_modeling_task.py, examples/evaluation/run_sequence_classification_task.py, examples/evaluation/run_text_summarization_task.py, examples/push_to_hub/push_quantized_model_to_hf_hub.py
This pr adds support for uploading and sharing quantized model, tokenizer and configs to Hugging Face Hub.
=> push_to_hub integration

auto_gptq/modeling/_base.py
Add option for GPTQ.
1. symmetric quantization
2. true sequential model
3. Additionally, i confirmed that the trits option does not work. Therefore, the trits option was not added.
=> add option

auto_gptq/modeling/_base.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/_utils.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/gpt2.py, auto_gptq/nn_modules/qlinear.py, auto_gptq/nn_modules/qlinear_triton.py, auto_gptq/quantization/gptq.py
fix bug about it
ValueError: wf is on the meta device, we need a value to put in on cuda:0.
and 
support gpt2
=> Fix bug speedup quant and support gpt2

auto_gptq/nn_modules/qlinear.py, auto_gptq/nn_modules/qlinear_triton.py, examples/quantization/basic_usage_gpt_xl.py
Added simple example for GPT2-xl.
Also, the current triton assumes that infeature and outfeature are divisible by 256. Because of this, triton does not work with GPT2-XL.
=> Add raise exception and gpt2 xl example add

README.md, docs/tutorial/02-Advanced-Model-Loading-and-Best-Practice.md, quant_cuda/quant_cuda_kernel.cu
I've realized that there is a bug in cuda users that makes a huge difference in the results. This is the code to fix it.
=> Fix bug cuda

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear_old.py, quant_cuda/quant_cuda.cpp, quant_cuda/quant_cuda_kernel.cu
Provides faster speed than triton if act-order and groupsize are not used at the same time.
=> Faster cuda no actorder

.gitignore, setup.py
1. On my system, setup complained about the "v" in version.
2. I added a detection for conda site package cuda include directory and add to include directories.
3. Added Python .gitignore
=> Setup conda

auto_gptq/modeling/_const.py, auto_gptq/modeling/gptj.py, auto_gptq/nn_modules/fused_gptj_attn.py, auto_gptq/nn_modules/fused_llama_attn.py, auto_gptq/utils/import_utils.py, setup.py
This pr adds `FusedLlamaAttentionForQuantizedModel`, gains 50%+ speed up in 4bit quantized GPTJ model compares to fp16 when `not desc_act or group_size == -1` and `inject_fused_attention=True`
=> Gptj fused attention

auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/llama.py
This pr extend `device_map` in from_quantized to support users customized config, as discussed in #47
=> Support users customize `device_map`

examples/quantization/basic_usage.py, examples/quantization/basic_usage_gpt_xl.py, examples/quantization/basic_usage_wikitext2.py, examples/quantization/quant_with_alpaca.py
It will help with people unwittingly making incompatible models. I will double check this when making NeoX20b-int4
=> Update example script to include desc_act

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/_fused_base.py, auto_gptq/nn_modules/fused_llama_mlp.py, auto_gptq/nn_modules/qlinear_triton.py, auto_gptq/nn_modules/triton_utils/__init__.py, auto_gptq/nn_modules/triton_utils/kernels.py, auto_gptq/nn_modules/triton_utils/mixin.py, auto_gptq/utils/import_utils.py, examples/quantization/quant_with_alpaca.py
this pr fix ImportError when triton is not installed and optimize codes to make it more automatic when trying to integrate with triton.
=> fix ImportError when triton is not installed

auto_gptq/nn_modules/triton_utils/kernels.py
Changed the code to support float32 with a simple code change. I expect this to make backward more stable.
=> triton float32 support

auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py
Re-pull request of https://github.com/PanQiWei/AutoGPTQ/pull/139 to avoid conflicts.
=> Add transpose operator when replace Conv1d with qlinear_cuda_old

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/baichuan.py
Adds support for the BaiChuan model. Requires `trust_remote_code`
[baichuan-inc/baichuan-7B](https://huggingface.co/baichuan-inc/baichuan-7B)
Initial testing indicates it seems to perform well speed wise.
Was requested in #162
=> Add support for BaiChuan model

auto_gptq/nn_modules/qlinear/qlinear_cuda.py, autogptq_cuda/autogptq_cuda_256.cpp, autogptq_cuda/autogptq_cuda_64.cpp, autogptq_cuda/autogptq_cuda_kernel_256.cu, autogptq_cuda/autogptq_cuda_kernel_64.cu
Fixed a bug where the 4bit kernel would not run and the 4bit old fast kernel would run instead.
I don't know why this happened, but it's probably my mistake.
=> Fix cuda bug

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/qwen.py
=> support qwen

.github/workflows/build_wheels_rocm.yml
Fixed some bugs when execute github workflow for building RoCM wheels.
=> Rocm build bug fix

.github/workflows/build_wheels_rocm.yml
As per title, we run into out of disk.
=> Free disk space for rocm build

auto_gptq/__init__.py, setup.py
=> Revert "V0.4.2 release"

auto_gptq/modeling/qwen.py
add transformer.visual as outside layer for the adaptation to Qwen-VL
=> Update qwen.py for Qwen-VL

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/fused_gptj_attn.py, auto_gptq/nn_modules/fused_llama_attn.py, auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py, auto_gptq/nn_modules/qlinear/qlinear_exllama.py, auto_gptq/nn_modules/qlinear/qlinear_triton.py, auto_gptq/nn_modules/triton_utils/kernels.py, autogptq_extension/cuda_256/autogptq_cuda_kernel_256.cu, autogptq_extension/cuda_64/autogptq_cuda_kernel_64.cu, autogptq_extension/exllama/cuda_func/q4_matmul.cu, autogptq_extension/exllama/cuda_func/q4_matrix.cu, autogptq_extension/exllama/matrix.cuh, autogptq_extension/qigen/generate.py
Reverts PanQiWei/AutoGPTQ#325 for it may breaks exllama kernels
=> Revert "fix bug(breaking change) remove (zeors -= 1)"

autogptq_extension/qigen/generate.py, setup.py
Up to now, despite QiGen kernel failing, the build of AutoGPTQ would continue, resulting in cryptic errors later on.
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/333
=> Fix QiGen kernel generation

auto_gptq/nn_modules/fused_llama_mlp.py, setup.py
As per title - for safety https://github.com/PanQiWei/AutoGPTQ/issues/307
=> Pin to accelerate>=0.22

autogptq_extension/exllama/exllama_ext.cpp
As per title.
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/318
=> Fix overflow in exllama with act-order

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/modeling/auto.py, auto_gptq/utils/import_utils.py, tests/test_q4.py
=> Default to exllama kernel when exllama v2 is disabled

auto_gptq/utils/exllama_utils.py, examples/benchmark/generation_speed.py, examples/benchmark/perplexity.py
=> Error out on exllama_set_max_input_length call without exllama backend

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/fused_gptj_attn.py, auto_gptq/nn_modules/fused_llama_attn.py, auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py, tests/test_q4.py
As per title.
This PR is a good reminder that untested contributions are just likely to be a nightmare to later maintain.
=> Fix dtype issues and add relevant tests

auto_gptq/utils/patch_utils.py, tests/test_q4.py
Follow up to https://github.com/PanQiWei/AutoGPTQ/pull/393, please refer to https://github.com/huggingface/accelerate/pull/2116
=> Patch accelerate to use correct dtype

autogptq_extension/exllama/exllama_ext.cpp
Fixes https://github.com/PanQiWei/AutoGPTQ/actions/runs/6734928614/job/18306906441
=> Fix Windows build

auto_gptq/nn_modules/qlinear/qlinear_qigen.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/peft_utils.py
As per title.
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/399 https://github.com/PanQiWei/AutoGPTQ/issues/404
=> Fix windows support

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, tests/test_quantization.py
As per title.
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/401
=> Fix quantize method with None mask

auto_gptq/utils/exllama_utils.py, autogptq_extension/exllama/cuda_func/q4_matmul.cu
=> Improve message about buffer size in exllama v1 backend

auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_exllama.py, auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py, auto_gptq/nn_modules/qlinear/qlinear_qigen.py, auto_gptq/nn_modules/qlinear/qlinear_triton.py, auto_gptq/utils/peft_utils.py, tests/test_q4.py
As per title, supersede https://github.com/PanQiWei/AutoGPTQ/pull/409
=> Fix windows (no triton) and cpu-only support

setup.py
=> Add option to disable qigen at build

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/fused_llama_attn.py
Compatible with https://github.com/huggingface/transformers/pull/26681
=> Fix compatibility with transformers 4.36

autogptq_extension/exllama/hip_compat.cuh
This is to resolve this issue: 
https://github.com/AutoGPTQ/AutoGPTQ/issues/510
=> rocm6.0 compatible exllama

auto_gptq/nn_modules/qlinear/qlinear_marlin.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/marlin_utils.py, autogptq_extension/marlin/marlin_cuda.cpp, autogptq_extension/marlin/marlin_cuda_kernel.cu, autogptq_extension/marlin/marlin_cuda_kernel.cuh, autogptq_extension/marlin/marlin_repack.cu, autogptq_extension/marlin/marlin_repack.cuh, setup.py, tests/test_repacking.py
Courtesy of @chu-tianxiang @ https://gist.github.com/chu-tianxiang/606f2be92b131dc4a5c1634f089b678c
=> Marlin repacking CUDA kernel

.github/workflows/build_wheels_cuda.yml, .github/workflows/build_wheels_pypi.yml, .github/workflows/build_wheels_rocm.yml, .github/workflows/test_quality.yml, auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py
Need to test first the impact of adding a `self.weight` and why it is needed. Seems like a bug in peft in the first place.
=> Disable peft compatibility

.github/workflows/build_wheels_cuda_linux.yml, .github/workflows/build_wheels_cuda_windows.yml, .github/workflows/build_wheels_pypi_linux.yml, .github/workflows/build_wheels_pypi_windows.yml
=> Dissociate Windows & Linux CUDA build

autogptq_extension/marlin/marlin_cuda_kernel.cu
Avoids some of
```
2024-02-16T10:24:15.8191443Z ptxas /tmp/tmpxft_00026252_00000000-13_marlin_cuda_kernel.compute_60.ptx, line 7532; error   : Feature 'ldmatrix' requires .target sm_75 or higher
2024-02-16T10:24:15.8192700Z ptxas /tmp/tmpxft_00026252_00000000-13_marlin_cuda_kernel.compute_60.ptx, line 7532; error   : Modifier '.m8n8' requires .target sm_75 or higher
2024-02-16T10:24:15.8193950Z ptxas /tmp/tmpxft_00026252_00000000-13_marlin_cuda_kernel.compute_60.ptx, line 7939; error   : Feature 'ldmatrix' requires .target sm_75 or higher
2024-02-16T10:24:15.8195190Z ptxas /tmp/tmpxft_00026252_00000000-13_marlin_cuda_kernel.compute_60.ptx, line 7939; error   : Modifier '.m8n8' requires .target sm_75 or higher
2024-02-16T10:24:15.8196419Z ptxas …
```
=> Add more guards on compute capability in Marlin kernel

auto_gptq/modeling/__init__.py
Was mistakenly removed in https://github.com/AutoGPTQ/AutoGPTQ/pull/537
Fixes https://github.com/AutoGPTQ/AutoGPTQ/issues/552
=> Add back missing import

auto_gptq/utils/marlin_utils.py, tests/test_q4.py, tests/test_serialization.py
Fixes https://github.com/AutoGPTQ/AutoGPTQ/issues/551
=> Fix bias materialization for Marlin

auto_gptq/nn_modules/qlinear/qlinear_marlin.py
Fixes https://github.com/AutoGPTQ/AutoGPTQ/issues/556
=> Fix shape check marlin

README.md, docs/INSTALLATION.md
=> Update install instructions on 0.7.1 release

examples/README.md
In `CUDA_VISIBLE_DEVICES=0 python generation_speed.py --model_name_pr_path PATH/TO/MODEL/DIR`
fix spelling mistake from `model_name_pr_path` to `model_name_or_path`
=> Fix spelling mistakes.

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/starcoder2.py
Adds support for [bigcode/starcoder2](https://huggingface.co/bigcode/starcoder2-15b) models.
Need to install the latest version of transformers from source.
=> Add starcoder2 support

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/phi.py
Attempt to address https://github.com/AutoGPTQ/AutoGPTQ/issues/575
This seems to work for me and I was able to make these models:
https://huggingface.co/mgoin/phi-2-super-gptq
https://huggingface.co/mgoin/phi-2-super-marlin
=> Add support for Phi models

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, setup.py
Fixes https://github.com/AutoGPTQ/AutoGPTQ/issues/604 cc @Qubitium
=> Fix quantization compatibility with transformers>=4.39

auto_gptq/modeling/_base.py, auto_gptq/utils/accelerate_utils.py, auto_gptq/utils/marlin_utils.py, tests/pytest.ini, tests/test_serialization.py
See details in https://github.com/huggingface/accelerate/pull/2588
TLDR `load_checkpoint_in_model` behavior when unexpected keys are in the checkpoint to be loaded is not well defined.
=> Patch load_checkpoint_in_model till accelerate 0.29

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/minicpm3.py
I am a staff member of Model Best. We have recently open sourced minicpm3.0. This is a model address that uses gtpq to quantify minicpm3.0. It has achieved good results. We look forward to your merger.
https://huggingface.co/openbmb/MiniCPM3-4B-GPTQ-Int4
=> support for minicpm3.0

auto_gptq/utils/peft_utils.py
The `PEFT_TYPE_TO_MODEL_MAPPING` variable was removed in PEFT PR https://github.com/huggingface/peft/pull/2282. This leads to an [error](https://github.com/huggingface/peft/actions/runs/12759828312/job/35564223487#step:7:69) when using AutoGPTQ with PEFT installed from main (and later starting with PEFT v0.15.0 once it is released).
This PR fixes this issue by using the `PEFT_TYPE_TO_TUNER_MAPPING` variable instead. The fix is implemented in a way that the code should continue to work with older PEFT versions while being compatible with the new PR.
Unrelated: The `QuantLinearHpu` import was re-ordered after I ran ruff on the file.
=> Fix import of mapping from PEFT
