examples/README.md, examples/quantization/basic_usage_wikitext2.py
This is a demo code using ppl to test the performance of AutoGPTQ.
opt - 125m
RTN baseline 37.27 ppl 
GPTQ for llama 29.21 ppl 
AutoGPTQ 29.87 ppl 
Some performance degradation is observed, but it seems to be a minor error.
=> add simple demo ppl test with wikitext2

auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py
`from_quantized()` has some hardcoded config that assumes a certain layout of files, e.g. `quantize_config.json` must be present and the model name must be `gptq_model-*`. All of it makes it impossible to load an arbitrary model, not created by AutoGPTQ itself (e.g. from HuggingFace Hub) without editing the model files.
This PR allows to specify custom `quantize_config`, `model_basename` and `trust_remote_code` params.
NOTES:
* There's a breaking change: `trust_remote_code` is now `False` by default. But I think it's better this way.
* I didn't add any docs.
* I didn't test this code with `*.index.json` files. Are they even supported here in the first place?
=> Allow to load arbitrary models

auto_gptq/modeling/_base.py, examples/quantization/basic_usage.py, examples/quantization/basic_usage_gpt_xl.py, examples/quantization/basic_usage_wikitext2.py
Currently, BaseQuantizeConfig is arranged in alphabetical order. However, this is odd given the importance of groupsize.
Also, considering that there is no problem in loading a model with only groupsize and bit, it seems good to change bit and groupsize to be saved together as names.
ex) gptq_model-{bits}bits.pt -> gptq_model-{bits}bits-{groupsize}g.pt
=> Change save name

auto_gptq/modeling/_base.py
Very simple fix that checks that the model exists before trying to load it.
Without this, if the user passes the wrong folder/file name, they get this error:
```
ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint, but got /workspace/stable-vicuna-13B-GPTQ/stable-vicuna-13B-GPTQ-4bit1.latest.act-order.safetensors.
```
I found this quite confusing because it does not clearly indicate that the file was not found at all.
With this PR, the user will now get:
```
FileNotFoundError: Could not find model at /workspace/stable-vicuna-13B-GPTQ/stable-vicuna-13B-GPTQ-4bit1.latest.act-order.safetensors
```
=> Check that model_save_name exists before trying to load it, to avoid confusing checkpoint error

auto_gptq/modeling/_utils.py
In `auto_gptq/modeling/_utils.py:pack_model`, argument `desc_act` is missing when calling `make_quant`. 
While using cuda, desc_act and grouping at the same time, `pack_model` and `make_quant` will have different implementation of `QuantLinear`, which results in empty `qlayers`.
=> fix incorrect pack while using cuda, desc_act and grouping

auto_gptq/modeling/_base.py
Fix for https://github.com/PanQiWei/AutoGPTQ/issues/81
Allows following code to work unaltered:
```
outputs = self._model(tokens[:, batch_start:batch_start+batch_size]
```
=> Forward position args to allow `model(tokens)` syntax

auto_gptq/modeling/auto.py
Minor syntax fix, error while running autogptq from latest branch:
```
File "/workdir/venv/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 25                                                                
"codegen": CodeGenGPTQForCausalLM                                                                                                                  
^^^^^^^^^                                                                                                                                          
SyntaxError: invalid syntax
```
=> Minor syntax fix for auto.py

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_base.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/_utils.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/rw.py, examples/quantization/basic_usage_gpt_xl.py
Add falcon
Added dtype. This is added because falcon currently does not support float16.
Also, the input dimension of 7b is not divisible by 256, so triton is not supported. This is a problem to be addressed later.
=> Falcon support

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py, auto_gptq/utils/peft_utils.py
Changed to automatically switch to pytorch backend when trainable is enabled in cuda backend.
This trains at roughly 1.3x (70 minutes --> 90 minutes) slower pace than triton, but has the advantage of not using triton.
=> Pytorch qlinear

.github/workflows/build_wheels.yml, setup.py
- Fixed compiling Cuda wheels. Required edit of `setup.py` to allow GitHub Actions to bypass `torch.cuda.is_available()`
- Added extended arch support for Cuda 11.8+
- Added uploading of sdist and non-Cuda wheel.
Successful test run here: https://github.com/jllllll/AutoGPTQ/actions/runs/5150921771
=> Fix and extend build_wheels.yml workflow

setup.py
This PR adds an explicit UTF-8 encoding argument to the `read_text` call when reading README.md in setup.py. Without specifying the encoding, it defaults to the system encoding, which can cause issues on Windows systems where UTF-8 is not the norm. Some codepages will raise a UnicodeDecodeError due to the exotic characters (e.g., emojis) present in the README.md file.
=> Specify UTF-8 encoding for README.md in setup.py

examples/benchmark/generation_speed.py
`examples/benchmark/generation_speed.py`: little fix that allows setting inject_fused_attention and inject_fused_mlp to False during benchmarking
=> Support setting inject_fused_attention and inject_fused_mlp to False

auto_gptq/nn_modules/qlinear/qlinear_triton.py
Stumbled upon this on an earlier version trying to Quantize a Falcon-7b (no success so far)
This model has non 256 multiples of features and was triggering this error.
However, the label of the error did not match the test.
Both in_feature and out_feature need to be divisible to fullfill the test abvoe.
=> Fix error message

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/internlm.py
add support for https://github.com/InternLM/InternLM
generate result in cczhong/internlm-chat-7b-4bit-gptq and we can use as expected.
=> Add support for InternLM

auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py
These kwargs were not being passed through to `.from_quantized()` so none of them were working.  That's now fixed.
I also fixed it so that huggingface_hub args are used for the `AutoGPTQFromCausalLM.from_pretrained()` call, so a model can be loaded direct from the hub including using revision or token and then quantized and pushed back to hub as GPTQ.
=> Fix `revision` and other huggingface_hub kwargs in .from_quantized()

setup.py
CUDA extension is now always built, which is required since 0.3.0 because without the CUDA extension, code will throw an error about not being able to load `autogptq_cuda_256`.
Therefore `GITHUB_ACTIONS=true` is no longer needed or used.
The new code also attempts to get the CUDA version from Torch, so that it can always be added to the version number when found, as in:
```
auto-gptq-0.3.0+cu118
```
(previously this +cuXXX was only added in GITHUB_ACTIONS)
I believe this will solve most or all of the installation problems people are having, where the CUDA extension is not installed.
If a user does NOT want the extension to build, they can still pass `BUILD_CUDA_EXT=0` as before.  However currently that will cause AutoGPTQ to fail to work (due to the error about not being able to find …
=> Change the install script so it attempts to build the CUDA extension in all cases

auto_gptq/__init__.py, setup.py
A very simple change that adds `__version__` to `__init__.py` so that we can do:
```
>>> import auto_gptq
>>> print(auto_gptq.__version__)
0.3.1
```
I also slightly modified the version number setting in setup.py to make it easier to edit, it's part of the metadata dict now, and then this is appended to with +cuXXX if appropriate.
Note: this PR is relative to: https://github.com/PanQiWei/AutoGPTQ/pull/206
=> Add a central version number

auto_gptq/__init__.py, auto_gptq/modeling/_base.py, setup.py
This PR adds some simple metadata to each saved `.safetensor` file, by passing a dict to `safe_save`.
It also allows the user to save any custom metadata, via new optional parameter in `.quantized()`: `safetensors_metadata`.
Reason one: it gets rid of this warning which users are regularly confused about:
```
2023-07-25 12:00:50 WARNING [accelerate.utils.modeling] The safetensors archive passed at /workspace/llama2-64g/gptq_model-4bit-64g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
```
Reason two: it provides the ability to store some information that could be useful in future, if clients start to read them.
With this PR, the following values are automatically stored in the metadata of every quantized …
=> Add Safetensors metadata saving, with some values saved to each .safetensor file

auto_gptq/utils/__init__.py, auto_gptq/utils/perplexity_utils.py, examples/benchmark/perplexity.py
Perplexity: *Intuitively, it can be thought of as an evaluation of the model’s ability to predict uniformly among the set of specified tokens in a corpus.* We leverage @TheBloke's replication of llama.cpp perplexity in #70 and build a functioning class that is flexible to calculate perplexity on the standard `wikitext` dataset.
For example, GPT2 scores `27.2268` on wikitext and `49.7432` on Shakespeare, meanwhile the GPTQ open-llama 7B scores `8.3029` in perplexity.
It has been implemented in utils because when you install AutoGPTQ, you can easily import it to check perplexity against any of your GPTQ models. 
The very basic API will automatically load your transformer onto the most powerful device on your machine and calculate perplexity:
```python
from auto_gptq.utils import Perplexity …
```
=> [FEATURE] Implement perplexity metric to compare against llama.cpp

auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py
This pr fix the error raised when CUDA kernels are not installed by setting `autogptq_cuda_256` and `autogptq_cuda_64` to None when checking failed.
=> Fix error raised when CUDA kernels are not installed

setup.py
This PR deploys a small fix to make sure the build succeeds on non-CUDA machines.
#206 introduced a slight change in the build that causes AutoGPTQ to fail on build on non-CUDA machines. However, there are parts of AutoGPTQ, like calculating perplexity, that does not require CUDA to run.
Resolves #211
=> Fix build on non-CUDA machines after #206

auto_gptq/modeling/_base.py
This is kind of critical @PanQiWei. The `revision` argument is ignored, which may lead to the wrong kernel being loaded.
=> Fix revision used to load the quantization config

auto_gptq/nn_modules/qlinear/__init__.py
Hi all, I have implemented support for  loading auto-gptq  pre-quantized checkpoints into MLC-LLM (based on the release 0.1.0 ). However this flow has encountered some issues with the `GeneralQuantLinear` in the release later than 0.2.0 has some issues of the load flow.
As from the compiler side, we load params with three different ways: named_buffers(), named_paramters(), state_dicts(), however, because the qweight, qzeros is not  registered in the GeneralQantLinear,  which means we cannot retrieve them using any of these methods.
This issue prevents us from fully utilizing the pre-quantized auto-gptq checkpoints in MLC-LLM. I believe addressing this issue will significantly enhance the functionality and flexibility of our model loading or post processing.
Thanks, and please CC @PanQiWei
=> [General Quant Linear] Register quant params of general quant linear for friendly post process.

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/fused_gptj_attn.py, auto_gptq/nn_modules/fused_llama_attn.py, auto_gptq/quantization/gptq.py
Adds static groups, a new feature of GPTQ.
Also fix disable exllama not working on fused attention.
=> Suppprt static groups and fix bug

auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_exllama.py
As per title, it would help if we can include this in a patch release before releasing on pypi, this would help make the integration with transformers smoother.
Avoids the unwanted warnings
```
Some weights of BloomForCausalLM were not initialized from the model checkpoint at /tmp/tmpgb5gyoq_ and are newly initialized: ['transformer.h.0.mlp.dense_4h_to_h.g_idx', 'transformer.h.16.self_attention.query_key_value.g_idx', 'transformer.h.23.mlp.dense_4h_to_h.g_idx'...]
```
cc @PanQiWei @SunMarc
=> Patch exllama QuantLinear to avoid modifying the state dict

.github/workflows/build_wheels_cuda.yml, .github/workflows/build_wheels_rocm.yml
Currently, wheels are built on ubuntu 22.04 against libc 2.32, which breaks on ubuntu 20.04 systems that support only libc 2.31: `ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32'`
=> Build wheels on ubuntu 20.04

.github/workflows/build_wheels_rocm.yml
We need it to build for different python versions.
=> Use conda incubator for rocm build

.github/workflows/build_wheels_rocm.yml
Revert https://github.com/PanQiWei/AutoGPTQ/pull/276. It appears that this action https://github.com/PanQiWei/AutoGPTQ/actions/runs/5950822354 used python 3.8 in all workflows for an unknown reason.
While https://github.com/PanQiWei/AutoGPTQ/actions/runs/5952031047 is successful.
=> Fix python version for rocm build

auto_gptq/__init__.py, auto_gptq/modeling/_base.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/_utils.py, auto_gptq/utils/exllama_utils.py, autogptq_cuda/exllama/cuda_func/q4_matmul.cu, autogptq_cuda/exllama/exllama_ext.cpp, tests/test_q4.py
Exllama requires to set a buffer on the C++ side in the act-order case, so as to reorder the activations. Although by default this buffer is of length 2048, we provide an API to allow to change the size of this buffer:
```
from auto_gptq import exllama_set_max_input_length
model = exllama_set_max_input_length(model, 4096)
```
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/253
Test with: `CUDA_VISIBLE_DEVICES=0 pytest tests/test_q4.py -k "test_exllama_buffer_size" -s`
@PanQiWei I think it would be worth a patch release, what do you think?
=> Expose a function to update exllama max input length

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_qigen.py, auto_gptq/utils/import_utils.py, setup.py
qigen currently does not support windows. Therefore, we made it so that qigen is not installed on Windows.
Currently, I can make Windows generate qigen's backend.cpp, but pytorch fails to compile backend.cpp.
=> Install skip qigen(windows)

auto_gptq/modeling/_base.py
The previous `BaseGPTQForCausalLM.to` returns internal `model` object which changed object type:
```python
def to(self, device: Union[str, torch.device]):
return self.model.to(device)
```
After fixing this bug, it always returns itself so object type will not be changed:
```python
def to(self, device: Union[str, torch.device]):
self.model.to(device)
return self
```
=> fix model type changed after calling .to() method

auto_gptq/modeling/_utils.py
This PR fixes a typo in `autogptq_post_init` which trigger an error when we want to change `max_input_length`.
=> fix typo in max_input_length

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/modeling/auto.py, auto_gptq/nn_modules/fused_gptj_attn.py, auto_gptq/nn_modules/fused_llama_attn.py, auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py, auto_gptq/utils/import_utils.py, autogptq_extension/exllamav2/config.h, autogptq_extension/exllamav2/cpp/util.h, autogptq_extension/exllamav2/cuda/compat.cuh, autogptq_extension/exllamav2/cuda/matrix_view.cuh, autogptq_extension/exllamav2/cuda/q_gemm.cu, autogptq_extension/exllamav2/cuda/q_gemm.cuh, autogptq_extension/exllamav2/cuda/q_gemm_kernel.cuh, autogptq_extension/exllamav2/cuda/q_gemm_kernel_gptq.cuh, autogptq_extension/exllamav2/cuda/q_matrix.cu, autogptq_extension/exllamav2/cuda/q_matrix.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_2.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_3.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_4.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_5.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_6.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_8.cuh, autogptq_extension/exllamav2/cuda/quant/qdq_util.cuh, autogptq_extension/exllamav2/cuda/util.cuh, autogptq_extension/exllamav2/ext.cpp, setup.py, tests/test_q4.py
This PR adds the [exllamav2](https://github.com/turboderp/exllamav2) kernels into auto-gptq. The integration is similar to the exllama kernel. Here's a quick benchmark with llama2-7B with the integration in optimum/transformers. We get slower speedup compared to the benchmark in exllamav2 repo because here we only replace the Linear layers with the quantized layer with exllamav2 kernel. I have confirmed that the tests were successful and that we have the same perplexity as exllama kernel. For now, we only support GPTQ format and not the new EXL2 format.
TLDR: for bs=4, we have the same speed as the llama model from exllamav2 repo and 40% faster than exllama kernel. 
For exllama kernel, we see that we are not compute bound for bs=1 and bs=2 and memory/overhead bound for bs=4. 
| …
=> exllamav2 integration

auto_gptq/utils/peft_utils.py
We have the following function to initialize PEFT adapters:
```python
def get_gptq_peft_model(
model: BaseGPTQForCausalLM,
peft_config: PeftConfig = None,
model_id: str = None,
adapter_name: str = "default",
auto_find_all_linears: bool = True,
train_mode: bool = False
):
```
However, by default it only uses the `adapter_name` parameter for the case when `train_mode=False`:
```python
with hijack_peft_mappings():
try:
if train_mode:
peft_model = get_peft_model(model.model, peft_config)
else:
peft_model = PeftModel.from_pretrained(model.model, model_id, adapter_name)
except:
raise NotImplementedError(
f"{model.__class__.__name__} not support {peft_config.peft_type.value} peft type yet."
)
```
So for instance if I called the function with the `chain-of-thoughts` adapter name - the …
=> Use `adapter_name` for `get_gptq_peft_model` with `train_mode=True`

auto_gptq/modeling/_base.py
The new version of AutoGPTQ added a new parameter into the `quantize_config.json` called `static_groups`. Now, if you have a model that was quantized with a new AutoGPTQ version and try to load it with an old AutoGPTQ version, you will get an error:
```
TypeError: BaseQuantizeConfig.__init__() got an unexpected keyword argument 'static_groups'
```
The newly created model is still compatible with the old AutoGPTQ version, but the extra parameter prevents the model from loading.
This PR makes it so all the unknown parameters in the `quantize_config.json` are ignored (and the warning is displayed). This ensures at least a minimal forward compatibility for the future AutoGPTQ versions.
=> Ignore unknown parameters in quantize_config.json

auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py
Changes:
-- The change to the torch.bitwise_and is done because during
tracing this model the current usage of the torch.bitwise_and
result in an in-place variant of this op, resulting in an issue
during the downstream lowering pipeline of the traced model via
Torch-MLIR and IREE-SHARK. That's why the op usage is changed to
not result in an in-place variaunt.
-- The change to the torch.matmul call in the forward function is
done because currently, it assumes that the weights will always
be of fp16 type. But, when the model is executed for the float32
weights it results in an error. That's why the current change
cast the LHS of the matmul to the same type as the RHS one.
Both the above changes doesn't affect the model in any way.
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>
=> Modify qlinear_cuda for tracing the GPTQ model

auto_gptq/modeling/_base.py, auto_gptq/modeling/auto.py, auto_gptq/nn_modules/triton_utils/custom_autotune.py, examples/benchmark/generation_speed.py
As per title. Fix a few import bugs with recent Triton version as well.
Fixes https://github.com/PanQiWei/AutoGPTQ/issues/332
=> Allow using a model with basename `model`, use_safetensors defaults to True

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/mistral.py
Adds support for [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1)
Requires [Transformers v4.34.0](https://github.com/huggingface/transformers/releases/tag/v4.34.0)
Inference tested using [TheBloke/Mistral-7B-v0.1-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-v0.1-GPTQ)
Quantization not tested.
Closes #359
=> Add support for Mistral models.

auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_cuda.py, auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>
=> Add fix for CPU Inference

autogptq_extension/qigen/generate.py
While building auto-gptq for ROCm 5.6, I encountered the following error. 
```  Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [60 lines of output]
In file included from ./autogptq_extension/qigen/mmm.cpp:2:
./autogptq_extension/qigen/forward.h: In function ‘void pack_input(float*, float*)’:
./autogptq_extension/qigen/forward.h:172:3: error: ‘uint64_t’ was not declared in this scope
172 |   uint64_t idx = 0;
|   ^~~~~~~~
./autogptq_extension/qigen/forward.h:4:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
3 | #include<fstream>
+++ |+#include <cstdint>
4 |
./autogptq_extension/qigen/forward.h:181:28: error: ‘idx’ was not declared in this scope …
```
=> Fixed missing cstdint include

auto_gptq/nn_modules/qlinear/qlinear_triton.py
Fixes `TypeError: QuantLinear.__init__() got an unexpected keyword argument 'weight_dtype'` by adding **kwargs.
@fxmarty just a simple fix, triton was completely unusable.
=> Fix triton unexpected keyword

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/yi.py
Adds support for [01-ai/Yi](https://huggingface.co/01-ai/Yi-6B) models.
Quantization/inference tested with [01-ai/Yi-6B](https://huggingface.co/01-ai/Yi-6B)
Set `transformers=>4.34.0` even though the model is not supported by it yet, this was the req in their [repo](https://github.com/01-ai/Yi/blob/main/requirements.txt).
Use `trust_remote_code=True`
Since the model is actually very close to Llama, `FusedLlamaAttentionForQuantizedModel` and `FusedLlamaMLPForQuantizedModel` are added. I tested them and if they actually were used(no errors, same output) then they should be working. I'm not 100% since it seems triton isn't working and I had to make my own fix which seemed to work.(not in this PR. Added **kwargs to qlinear_triton init)
@TheBloke would be great if you could do a bit of a …
=> Add support for Yi models.

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/xverse.py
Adds support for [xverse/XVERSE](https://huggingface.co/xverse/XVERSE-7B) models.
Quantization/inference tested with [xverse/XVERSE-7B](https://huggingface.co/xverse/XVERSE-7B)
Ver. 2 of the models are just further training, so they should work fine.
Very close to Llama, so `FusedLlamaAttentionForQuantizedModel` and `FusedLlamaMLPForQuantizedModel` are enabled.
`trust_remote_code=True` required.
=> Add support for Xverse models.

auto_gptq/modeling/_base.py
Whats happening - 
```.bin``` Model is unable to load - FIleNotFound error.
When you load a model from huggingface remotely with ```use_safetensors = False```, there are two extensions to work with - ```.bin```, ```.pt```.  
Line 834, checks the cached model directory for the model base name with the above extensions in the same order as above.
Case - 1: If no model found with either extensions, the original code works as expected (throws error).
Case - 2: If models with both extensions found or if only ```.pt``` extension is found, the model with ```.pt``` extension loads. Although in the former case, the user has no liberty to choose between the two models.
Case - 3: If only ```.bin``` model exists. then it throws a FileNotFoundError as in the first case.
The fix - 
A simple fix with …
=> Update _base.py - Remote (.bin) model load fix

auto_gptq/modeling/_base.py
This skips make_quant on layers not defined in inside_layer_modules for the model.
Allows model definitions to properly control which modules should be quantized and converted to QuantLinear.
This should fix inference errors with incompatible modules. For example required for Mixtral and could help with vision modules and such.
Similar to https://github.com/huggingface/optimum/pull/1585
=> Only make_quant on inside_layer_modules.

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/decilm.py
Adds support for [Deci/DeciLM-7B](https://huggingface.co/Deci/DeciLM-7B) models.
Quantization/Inference tested with the above model.
`trust_remote_code=True` required.
`FusedLlamaAttentionForQuantizedModel` and `FusedLlamaMLPForQuantizedModel` are enabled.
=> Add support for DeciLM models.

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_base.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/mixtral.py, tests/test_q4.py
Adds support for [mistralai/Mixtral-8x7B-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-v0.1)
Quantization/inference tested also with [hf-internal-testing/Mixtral-tiny](https://huggingface.co/hf-internal-testing/Mixtral-tiny)
Requires #479 for working inference.
`transformers>=4.36.0` + for transformers inference requires https://github.com/huggingface/transformers/pull/27956
Fixes #476
=> Add support for Mixtral models.

auto_gptq/modeling/_base.py
See https://github.com/PanQiWei/AutoGPTQ/issues/370#issuecomment-1766913012
=> fix the support of Qwen

auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py
DeciLM (implemented in #481) added model_type to their config which changed the type from `deci_lm` to `deci`
This is just a simple fix to follow that naming.
Thanks @RajdeepBorgohain for bringing this to my attention.
https://github.com/PanQiWei/AutoGPTQ/commit/97ba340e46cc9920e678fe734f9b04ca8bf18357#r135555067
=> Change deci_lm model type to deci

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_marlin.py, auto_gptq/utils/marlin_utils.py, tests/test_q4.py, tests/test_serialization.py
PR does a couple things:
- moves the repacking logic to `marlin_utils.py`
- supports saving the model with `is_marlin_format` in the gptq config, such that during reload we can load directly
- implements reloading a marlin_serialized model
I introduced some terminology:
- `is_marlin_serialized` --> in this case, the stub / local path actually has a marlin model saved
- `is_marlin_cached` --> in this case, there is a cached marlin model available in `assets`
- else --> in this case, we need to repack the model
Testing:
```bash
import gc
import torch
from transformers import AutoTokenizer
from auto_gptq import AutoGPTQForCausalLM
model_id = "TheBloke/Llama-2-7B-Chat-GPTQ"
tokenizer = AutoTokenizer.from_pretrained(model_id)
def generate(model):
inputs = tok("Hello my name is", …
```
=> updated marlin serialization

auto_gptq/modeling/_base.py, auto_gptq/nn_modules/qlinear/qlinear_marlin.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/marlin_utils.py, auto_gptq/utils/modeling_utils.py, setup.py
Safetensors is unable to handle tied weights as reported in https://github.com/AutoGPTQ/AutoGPTQ/pull/524/files#r1474229087 & https://github.com/huggingface/safetensors/issues/202
=> Untie weights for safetensors serialization

auto_gptq/modeling/__init__.py, auto_gptq/modeling/_const.py, auto_gptq/modeling/auto.py, auto_gptq/modeling/gemma.py
Adds support for [google/gemma](https://huggingface.co/google/gemma-7b) models.
I would like some more testing though because my results were very repetitive generation. [could be related?](https://huggingface.co/google/gemma-7b/discussions/33)
Requires `transformers>=4.38.0`
=> Add support for Gemma models.

auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_marlin.py
Some people may use Marlin's QLinear without using the `from_quantized` method. Hence the check there as well.
Also fix an issue due to a transformers breaking backward compatibility issue https://github.com/huggingface/transformers/pull/29299
=> Explicitely check compute capability in marlin's QLinear

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_marlin.py, tests/test_quantization.py
Fix Issue #581
Main branch cannot perform marlin quantization as show in example below due to is_marlin_format not read/applied from quantization_config:
```
quantize_config = BaseQuantizeConfig(
bits=4,  # quantize model to 4-bit
group_size=128,  # it is recommended to set the value to 128
desc_act=False,  # desc_act and group size only works on triton
damp_percent=0.005,
is_marlin_format=True
)
model = AutoGPTQForCausalLM.from_pretrained(pretrained_model_dir, quantize_config=quantize_config)
model.quantize(traindataset, use_triton=False)
model.save_quantized(quantized_model_dir)
```
Also fixed qlinear_marlin.py not correctly handling `linear.bias == None`. 
@chu-tianxiang  @fxmarty
=> Fix marlin quantization using BaseQuantizeConfig from _pretrained #581

auto_gptq/modeling/_utils.py
In `auto_gptq/modeling/_utils.py` removed redundant `scales` variable assignment as the first assignment is unused
=> Removing Redundant 'scales' Assignment

auto_gptq/modeling/_utils.py
Added missing `use_tritonv2` in `make_sure_no_tensor_in_meta_device` which was throwing an error.
=> fix tritonv2 in make_sure_no_tensor_in_meta_device

README.md
As per title.
Follow https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features.
For more context, see this very good summary https://github.com/Dao-AILab/flash-attention/issues/833#issuecomment-1953111510. On some recent systems, build isolation is default with pip (**apparently even though we don't have a pyproject.toml!**) which is very bad with PyTorch as in case we build in isolation, pytorch would be redownloaded, potentially with the wrong CUDA/ROCm version. I don't understand why this is default in pip now, but that's the way it is.
See also https://github.com/pypa/pip/issues/8437
=> Add --no-build-isolation to install instructions

README.md, setup.py
As per title. On an Nvidia build, we require can not build for Maxwell GPUs or lower.
=> Show meaningful error on Maxwell build

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, auto_gptq/quantization/__init__.py, auto_gptq/quantization/config.py, auto_gptq/utils/accelerate_utils.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/marlin_utils.py, tests/test_quantization.py, tests/test_serialization.py
Core reason for PR:
Unify the concept of model weight `format` since repo already have coding for 3 weight formats: gptq, marlin, and awq_gemm with 4th pending in #559. Without this PR, existing properties of different weight formats are fragmented and not forward compatible with new formats such as pending #559 which will require another property field. Have one single `format` field to unify them all.
Changes:
* MAJOR `format` unifies `is_marlin_format`,  `awq_qemm`, and pending `gptq_v2` format in pr #559
* `format` defaults to `gptq`
* MAJOR `gptq_method` remapped to `method` 
* MAJOR compat: pinned transformers to < 4.39.0 due to #604
* fix _validate_marlin_device_support() returns false for ada/hopper. Fix #616 
* fix  json arg normalization comparisons did not use lowercased keys …
=> Add checkpoint_format to unify all current/future saved weight formats

auto_gptq/nn_modules/qlinear/qlinear_exllama.py, auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py
While hacking away in the dbrx code in #625 I found apparent errors in exllama code where padding was calculated but never used triggering`assert outfeaters % 32  == 0` when it should not have.
PR:
1. fixed padding code for exllama v2 `outfeatures` not correctly applied
2. ported same padding code from v2 to v1
test_q4 passed. 
I am not sure how to test this since the current test_q4 does not contain tests that have models with `outfeatures` that require padding. 
@fxmarty
=> Fix padding not used correctly in exllama v2 layer

auto_gptq/modeling/_base.py, tests/test_quantization.py
This fix packing regression found in [#625 ](https://github.com/AutoGPTQ/AutoGPTQ/pull/625#issuecomment-2028647704)
The core cause is very strange and debilitating. Packing performance will slow down to a crawl on my env yet linux `load` value < cores by significant margin showing no thread oversubscription. Based on what I observe, launching more than 8 threads has zero to negative impact on `pack()`  performance. 
My estimation is that the extra threads are doing nothing but context switching (due to internal locks?) and performing very little actual work which results in the massive regression in packing. In fact, setting value to 1 is just as good but not as fast as 8. 
We can't fix this in code since the thread limit must happen before all any tensor libs are imported. I believe a …
=> Force warn users to reduce threads or packing may regress ~100x

auto_gptq/modeling/_utils.py, auto_gptq/nn_modules/qlinear/qlinear_hpu.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/peft_utils.py, tests/test_hpu_linear.py, tests/test_q4.py
Added native support in HPU, using a conversion kernel.
Currently we only support inference on a preloaded HF model.
This feature will be usable in Synapse v1.17
* Supporting llama uint4 inference using AutoGPTQ in HPU
* Removed hpu pack until we'll implement it in HPU
---------
=> Supporting uint4 inference of pre-quantized models in HPU

auto_gptq/modeling/_base.py, auto_gptq/modeling/_utils.py, setup.py, tests/pytest.ini, tests/test_quantization.py
Reason for PR:
* Packing has unfixed thread regression on env with lots of cpu cores. The more cores you have, the slower your packing time becomes. Non-linear regression.
* Previous fix was simple warning on injecting env vars.  https://github.com/AutoGPTQ/AutoGPTQ/pull/628
* PR fixes this issue, not the core cause, by limiting packing() context to use 1 thread. https://github.com/AutoGPTQ/AutoGPTQ/issues/439
However, this will need a new pkg depend: https://github.com/joblib/threadpoolctl 
>Python helpers to limit the number of threads used in native libraries that handle their own internal threadpool (BLAS and OpenMP implementations)
ref: https://github.com/AutoGPTQ/AutoGPTQ/pull/640#discussion_r1566931521
Tests Passed:
=> [PERFORMANCE] Fix Packing thread regression in code

auto_gptq/modeling/_base.py, auto_gptq/utils/import_utils.py, auto_gptq/utils/marlin_utils.py, autogptq_extension/marlin/marlin_cuda_kernel.cu
PR:
Backport H100 crash fix from vllm marlin kernel
TESTS:
Ref: https://github.com/vllm-project/vllm/pull/4218
=> [BUG] Fix H100 crash/compat with Marlin

auto_gptq/nn_modules/qlinear/qlinear_hpu.py, auto_gptq/utils/import_utils.py, tests/test_hpu_linear.py, tests/test_q4.py
Fixed import issue when HPU is not available.
Addressing the following discussion:
https://github.com/AutoGPTQ/AutoGPTQ/discussions/695
And after it was introduced in PR:
https://github.com/AutoGPTQ/AutoGPTQ/pull/689
=> Fix upstream regression when there's no HPU device

auto_gptq/modeling/_utils.py
Some models' QuantLinear doesn't have bias.
AutoGPTQForCausalLM.from_quantized will emit an error like:
```
Traceback (most recent call last):
File "/home/mjc/qwen-gptq-load.py", line 6, in <module>
model = AutoGPTQForCausalLM.from_quantized(
File "/home/mjc/AutoGPTQ/auto_gptq/modeling/auto.py", line 146, in from_quantized
return quant_func(
File "/home/mjc/AutoGPTQ/auto_gptq/modeling/_base.py", line 966, in from_quantized
make_sure_no_tensor_in_meta_device(
File "/home/mjc/AutoGPTQ/auto_gptq/modeling/_utils.py", line 522, in make_sure_no_tensor_in_meta_device
if isinstance(m, QuantLinear) and m.bias.device == torch.device("meta"):
AttributeError: 'NoneType' object has no attribute 'device'
```
So check it in make_sure_no_tensor_in_meta_device.
=> Fix error when loading quantized model with low_cpu_mem_usage is true

auto_gptq/modeling/auto.py
Looks like https://github.com/AutoGPTQ/AutoGPTQ/pull/731 suffered from last-minute renames, and an error crept in which breaks loading `auto_gptq`.
=> Quickfix for failure after merged PR 731

auto_gptq/nn_modules/qlinear/qlinear_exllama.py
The `for` loop operation in `pack` function is too slowly. I replace it with tensor operation. The operation is fully equivalent and significantly faster. In our tests, it achieved a 120x improvement on `Qwen2.5 3B` model.
=> fix the issue of qlinear packing being too slow.
